//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoSave.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoSave.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoSave could not connect to the test servers.
        ///
        ///Please check your internet connection and try again..
        /// </summary>
        internal static string ConnectionCheckFailedMessage_En {
            get {
                return ResourceManager.GetString("ConnectionCheckFailedMessage_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoSave не смог подключиться к тестовым серверам.
        ///
        ///Проверьте подключение к интернету и попробуйте снова..
        /// </summary>
        internal static string ConnectionCheckFailedMessage_Ru {
            get {
                return ResourceManager.GetString("ConnectionCheckFailedMessage_Ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoSave не вдалося підключитися до тестових серверів.
        ///
        ///Перевірте підключення до інтернету та спробуйте ще раз..
        /// </summary>
        internal static string ConnectionCheckFailedMessage_Uk {
            get {
                return ResourceManager.GetString("ConnectionCheckFailedMessage_Uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Check Failed.
        /// </summary>
        internal static string ConnectionCheckFailedTitle_En {
            get {
                return ResourceManager.GetString("ConnectionCheckFailedTitle_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка проверки подключения.
        /// </summary>
        internal static string ConnectionCheckFailedTitle_Ru {
            get {
                return ResourceManager.GetString("ConnectionCheckFailedTitle_Ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка перевірки підключення.
        /// </summary>
        internal static string ConnectionCheckFailedTitle_Uk {
            get {
                return ResourceManager.GetString("ConnectionCheckFailedTitle_Uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoSave could not verify that Windows Firewall rules are working.
        ///
        ///Please check Windows Firewall or disable third-party firewall software..
        /// </summary>
        internal static string FirewallCheckFailedMessage_En {
            get {
                return ResourceManager.GetString("FirewallCheckFailedMessage_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoSave не смог проверить, что правила Windows Firewall работают.
        ///
        ///Проверьте Windows Firewall или отключите сторонний фаервол..
        /// </summary>
        internal static string FirewallCheckFailedMessage_Ru {
            get {
                return ResourceManager.GetString("FirewallCheckFailedMessage_Ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoSave не вдалося перевірити, що правила Windows Firewall працюють.
        ///
        ///Перевірте Windows Firewall або вимкніть сторонній фаєрвол..
        /// </summary>
        internal static string FirewallCheckFailedMessage_Uk {
            get {
                return ResourceManager.GetString("FirewallCheckFailedMessage_Uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firewall Check Failed.
        /// </summary>
        internal static string FirewallCheckFailedTitle_En {
            get {
                return ResourceManager.GetString("FirewallCheckFailedTitle_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка проверки фаервола.
        /// </summary>
        internal static string FirewallCheckFailedTitle_Ru {
            get {
                return ResourceManager.GetString("FirewallCheckFailedTitle_Ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка перевірки фаєрвола.
        /// </summary>
        internal static string FirewallCheckFailedTitle_Uk {
            get {
                return ResourceManager.GetString("FirewallCheckFailedTitle_Uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register hotkey. 
        ///
        ///You can still use the button manually..
        /// </summary>
        internal static string HotkeyRegisterFailedMessage_En {
            get {
                return ResourceManager.GetString("HotkeyRegisterFailedMessage_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось зарегистрировать горячую клавишу. 
        ///
        ///Вы всё ещё можете использовать кнопку вручную..
        /// </summary>
        internal static string HotkeyRegisterFailedMessage_Ru {
            get {
                return ResourceManager.GetString("HotkeyRegisterFailedMessage_Ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вдалося зареєструвати гарячу клавішу.
        ///
        ///Ви все ще можете використовувати кнопку вручну..
        /// </summary>
        internal static string HotkeyRegisterFailedMessage_Uk {
            get {
                return ResourceManager.GetString("HotkeyRegisterFailedMessage_Uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey error.
        /// </summary>
        internal static string HotkeyRegisterFailedTitle_En {
            get {
                return ResourceManager.GetString("HotkeyRegisterFailedTitle_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка горячей клавиши.
        /// </summary>
        internal static string HotkeyRegisterFailedTitle_Ru {
            get {
                return ResourceManager.GetString("HotkeyRegisterFailedTitle_Ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка гарячої клавіші.
        /// </summary>
        internal static string HotkeyRegisterFailedTitle_Uk {
            get {
                return ResourceManager.GetString("HotkeyRegisterFailedTitle_Uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers are currently blocked.
        ///
        ///The game may not work in online mode until you unblock them.
        ///
        ///Close NoSave anyway?.
        /// </summary>
        internal static string ServersBlockedCloseWarningMessage_En {
            get {
                return ResourceManager.GetString("ServersBlockedCloseWarningMessage_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервера сейчас заблокированы.
        ///
        ///Игра может не работать в онлайн-режиме, пока вы их не разблокируете.
        ///
        ///Всё равно закрыть NoSave?.
        /// </summary>
        internal static string ServersBlockedCloseWarningMessage_Ru {
            get {
                return ResourceManager.GetString("ServersBlockedCloseWarningMessage_Ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервери зараз заблоковані.
        ///
        ///Гра може не працювати в онлайн-режимі, доки ви їх не розблокуєте.
        ///
        ///Усе одно закрити NoSave?.
        /// </summary>
        internal static string ServersBlockedCloseWarningMessage_Uk {
            get {
                return ResourceManager.GetString("ServersBlockedCloseWarningMessage_Uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers are blocked.
        /// </summary>
        internal static string ServersBlockedCloseWarningTitle_En {
            get {
                return ResourceManager.GetString("ServersBlockedCloseWarningTitle_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервера заблокированы.
        /// </summary>
        internal static string ServersBlockedCloseWarningTitle_Ru {
            get {
                return ResourceManager.GetString("ServersBlockedCloseWarningTitle_Ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервери заблоковані.
        /// </summary>
        internal static string ServersBlockedCloseWarningTitle_Uk {
            get {
                return ResourceManager.GetString("ServersBlockedCloseWarningTitle_Uk", resourceCulture);
            }
        }
    }
}
